version: "3.8"

services:

  GFPGAN:
    image: marcellodesales/tencent-arc-gfpgan-runtime
    build:
      context: .
      args:
        TENCENT_ARC_BASE_IMAGE: marcellodesales/ubuntu-python-ninja
        TRAINING_FILE1: v0.2.0/GFPGANCleanv1-NoCE-C2.pth
        TRAINING_FILE2: v0.1.0/GFPGANv1.pth
    environment:
      GFPGAN_UPSCALE: 2
      GFPGAN_MODEL_PATH: /app/experiments/pretrained_models/GFPGANCleanv1-NoCE-C2.pth
      GFPGAN_TEST_PATH: /app/inputs/cropped_faces
      GFPGAN_RESULTS_PATH: /app/results
    volumes:
      - ./build/experiments:/app/experiments
      - ./build/inputs:/app/inputs 
      - ./build/results:/app/results
